[WIP] Fix compilation errors for Clang 15
...though I haven't checked whether the fix is correct, and
check-templight doesn't work due to:
llvm-lit: /home/eumakri/Documents/llvm-project/llvm/utils/lit/lit/llvm/config.py:321: fatal: Could not turn '' into Itanium ABI triple